### ISSUE TITLE
Add EJS 2.x support

### ISSUE THREAD

**Issue by puzrin** [nodeca/mincer#180]
https://github.com/mde/ejs

2.0 is completely different, with new API. Needs update.

Note, repo link aslo changed. Actually, it's another project, published under the same name.

**Comment by AlphaHydrae** [comment]
I just ran into the same issue. It took a while to figure it out.

With EJS `2.*`, I get `foo is not defined` even though I registered a `foo` helper. It works with EJS `1.*`.

Note that with the current instructions in `examples/README.md`, EJS 2 is installed so the examples also fail:

```
`scope` option is deprecated and will be removed in EJS 3
Failed compile assets: [MacroProcessor] Failed to evaluate macro `JSON.stringify(asset_path("app.css"))` [[EjsEngine] /Users/unknow/Projects/mincer/examples/assets/stylesheets/app.css.ejs:6
    4| 
    5| body {
 >> 6|   background: url('<%= image_path('stripes.png') %>');
    7|   transition: transform 1s;
    8| }
    9| 

image_path is not defined  (in /Users/unknow/Projects/mincer/examples/assets/stylesheets/app.css.ejs)]  (in /Users/unknow/Projects/mincer/examples/assets/javascripts/app.js.coffee:11)
```

This is probably due to your instructions to install additional modules:

```
npm install connect less jade coffee-script haml-coffee ejs \
  uglify-js csso autoprefixer
```

Which will reinstall the latest version over the `~ 1.*` specified in `package.json`.

**Comment by puzrin** [comment]
Seems instruction is outdated ages ago. We dropped haml-coffe support too. Need to update it. As far as i remember, `npm install` is enougth now.

**Comment by puzrin** [comment]
Done by @jeremyruppel in 1.2.5
