### ISSUE TITLE
Better support for Bower

### ISSUE THREAD

**Issue by vjpr** [nodeca/mincer#58]
In [Bower](http://twitter.github.com/bower/), I find that I have to write `#= require underscore/underscore`. Can we have it so that if you require a directory, if it contains a file by the same name, that will be required. So that I can just write `#= require underscore`, without every library having to add an `index.js` file.

Alternatively, if we `require` a directory, it checks the directory for a `component.json` (Bower's `package.json` equivalent) and looks for the `main` property which is an array of the main files from this library. This would be ideal.

**Comment by wesleycoder** [comment]
I'm trying to require angular installed by bower, but I still have to require "angular/angular", just requiring "angular" gives me the angular's bower.json content instead of the main file referenced in it.

PS.: I'm using https://github.com/dapriett/sails-hook-mincer, but looking at the way it uses mincer it should work...
